# Generated by carnix 0.10.2: /home/daniel/.cargo/bin/carnix generate-nix --standalone --src .
{ lib, buildRustCrate, buildRustCrateHelpers, callPackage }:

with buildRustCrateHelpers;
let inherit (lib.lists) fold;
    inherit (lib.attrsets) recursiveUpdate;
  cratesIO = (callPackage ./crates-io.nix { });
in
rec {
  crates = cratesIO // rec {
# finalfusion-utils-0.8.1

    crates.finalfusion_utils."0.8.1" = deps: { features?(features_."finalfusion_utils"."0.8.1" deps {}) }: buildRustCrate {
      crateName = "finalfusion-utils";
      version = "0.8.1";
      description = "finalfusion utilities";
      homepage = "https://github.com/finalfusion/finalfusion-rust";
      authors = [ "Daniël de Kok <me@danieldk.eu>" ];
      edition = "2018";
      src = exclude [ ".git" "target" ] ./.;
      dependencies = mapFeatures features ([
        (cratesIO.crates."clap"."${deps."finalfusion_utils"."0.8.1"."clap"}" deps)
        (cratesIO.crates."env_logger"."${deps."finalfusion_utils"."0.8.1"."env_logger"}" deps)
        (cratesIO.crates."failure"."${deps."finalfusion_utils"."0.8.1"."failure"}" deps)
        (cratesIO.crates."finalfusion"."${deps."finalfusion_utils"."0.8.1"."finalfusion"}" deps)
        (cratesIO.crates."getopts"."${deps."finalfusion_utils"."0.8.1"."getopts"}" deps)
        (cratesIO.crates."ndarray"."${deps."finalfusion_utils"."0.8.1"."ndarray"}" deps)
        (cratesIO.crates."num_cpus"."${deps."finalfusion_utils"."0.8.1"."num_cpus"}" deps)
        (cratesIO.crates."rayon"."${deps."finalfusion_utils"."0.8.1"."rayon"}" deps)
        (cratesIO.crates."reductive"."${deps."finalfusion_utils"."0.8.1"."reductive"}" deps)
        (cratesIO.crates."stdinout"."${deps."finalfusion_utils"."0.8.1"."stdinout"}" deps)
        (cratesIO.crates."toml"."${deps."finalfusion_utils"."0.8.1"."toml"}" deps)
      ]);
      features = mkFeatures (features."finalfusion_utils"."0.8.1" or {});
    };
    features_."finalfusion_utils"."0.8.1" = deps: f: updateFeatures f (rec {
      clap."${deps.finalfusion_utils."0.8.1".clap}".default = true;
      env_logger."${deps.finalfusion_utils."0.8.1".env_logger}".default = true;
      failure."${deps.finalfusion_utils."0.8.1".failure}".default = true;
      finalfusion."${deps.finalfusion_utils."0.8.1".finalfusion}".default = true;
      finalfusion_utils."0.8.1".default = (f.finalfusion_utils."0.8.1".default or true);
      getopts."${deps.finalfusion_utils."0.8.1".getopts}".default = true;
      ndarray."${deps.finalfusion_utils."0.8.1".ndarray}".default = true;
      num_cpus."${deps.finalfusion_utils."0.8.1".num_cpus}".default = true;
      rayon."${deps.finalfusion_utils."0.8.1".rayon}".default = true;
      reductive = fold recursiveUpdate {} [
        { "${deps.finalfusion_utils."0.8.1".reductive}"."opq-train" =
          (f.reductive."${deps.finalfusion_utils."0.8.1".reductive}"."opq-train" or false) ||
          (finalfusion_utils."0.8.1"."opq" or false) ||
          (f."finalfusion_utils"."0.8.1"."opq" or false); }
        { "${deps.finalfusion_utils."0.8.1".reductive}".default = true; }
      ];
      stdinout."${deps.finalfusion_utils."0.8.1".stdinout}".default = true;
      toml."${deps.finalfusion_utils."0.8.1".toml}".default = true;
    }) [
      (if deps."finalfusion_utils"."0.8.1" ? "clap" then cratesIO.features_.clap."${deps."finalfusion_utils"."0.8.1"."clap" or ""}" deps else {})
      (if deps."finalfusion_utils"."0.8.1" ? "env_logger" then cratesIO.features_.env_logger."${deps."finalfusion_utils"."0.8.1"."env_logger" or ""}" deps else {})
      (if deps."finalfusion_utils"."0.8.1" ? "failure" then cratesIO.features_.failure."${deps."finalfusion_utils"."0.8.1"."failure" or ""}" deps else {})
      (if deps."finalfusion_utils"."0.8.1" ? "finalfusion" then cratesIO.features_.finalfusion."${deps."finalfusion_utils"."0.8.1"."finalfusion" or ""}" deps else {})
      (if deps."finalfusion_utils"."0.8.1" ? "getopts" then cratesIO.features_.getopts."${deps."finalfusion_utils"."0.8.1"."getopts" or ""}" deps else {})
      (if deps."finalfusion_utils"."0.8.1" ? "ndarray" then cratesIO.features_.ndarray."${deps."finalfusion_utils"."0.8.1"."ndarray" or ""}" deps else {})
      (if deps."finalfusion_utils"."0.8.1" ? "num_cpus" then cratesIO.features_.num_cpus."${deps."finalfusion_utils"."0.8.1"."num_cpus" or ""}" deps else {})
      (if deps."finalfusion_utils"."0.8.1" ? "rayon" then cratesIO.features_.rayon."${deps."finalfusion_utils"."0.8.1"."rayon" or ""}" deps else {})
      (if deps."finalfusion_utils"."0.8.1" ? "reductive" then cratesIO.features_.reductive."${deps."finalfusion_utils"."0.8.1"."reductive" or ""}" deps else {})
      (if deps."finalfusion_utils"."0.8.1" ? "stdinout" then cratesIO.features_.stdinout."${deps."finalfusion_utils"."0.8.1"."stdinout" or ""}" deps else {})
      (if deps."finalfusion_utils"."0.8.1" ? "toml" then cratesIO.features_.toml."${deps."finalfusion_utils"."0.8.1"."toml" or ""}" deps else {})
    ];


# end

  };

  finalfusion_utils = crates.crates.finalfusion_utils."0.8.1" deps;
  __all = [ (finalfusion_utils {}) ];
  deps.aho_corasick."0.7.6" = {
    memchr = "2.2.1";
  };
  deps.ansi_term."0.11.0" = {
    winapi = "0.3.7";
  };
  deps.arrayvec."0.4.11" = {
    nodrop = "0.1.13";
  };
  deps.atty."0.2.13" = {
    libc = "0.2.60";
    winapi = "0.3.7";
  };
  deps.autocfg."0.1.5" = {};
  deps.backtrace."0.3.34" = {
    backtrace_sys = "0.1.31";
    cfg_if = "0.1.9";
    libc = "0.2.60";
    rustc_demangle = "0.1.15";
  };
  deps.backtrace_sys."0.1.31" = {
    libc = "0.2.60";
    cc = "1.0.38";
  };
  deps.bitflags."1.1.0" = {};
  deps.blas_src."0.2.1" = {};
  deps.byteorder."1.3.2" = {};
  deps.cblas_sys."0.1.4" = {
    libc = "0.2.60";
  };
  deps.cc."1.0.38" = {};
  deps.cfg_if."0.1.9" = {};
  deps.clap."2.33.0" = {
    atty = "0.2.13";
    bitflags = "1.1.0";
    strsim = "0.8.0";
    textwrap = "0.11.0";
    unicode_width = "0.1.5";
    vec_map = "0.8.1";
    ansi_term = "0.11.0";
  };
  deps.cloudabi."0.0.3" = {
    bitflags = "1.1.0";
  };
  deps.crossbeam_deque."0.6.3" = {
    crossbeam_epoch = "0.7.2";
    crossbeam_utils = "0.6.6";
  };
  deps.crossbeam_epoch."0.7.2" = {
    arrayvec = "0.4.11";
    cfg_if = "0.1.9";
    crossbeam_utils = "0.6.6";
    lazy_static = "1.3.0";
    memoffset = "0.5.1";
    scopeguard = "1.0.0";
  };
  deps.crossbeam_queue."0.1.2" = {
    crossbeam_utils = "0.6.6";
  };
  deps.crossbeam_utils."0.6.6" = {
    cfg_if = "0.1.9";
    lazy_static = "1.3.0";
  };
  deps.derive_new."0.5.7" = {
    proc_macro2 = "0.4.30";
    quote = "0.6.13";
    syn = "0.15.42";
  };
  deps.either."1.5.2" = {};
  deps.env_logger."0.6.2" = {
    atty = "0.2.13";
    humantime = "1.2.0";
    log = "0.4.8";
    regex = "1.2.1";
    termcolor = "1.0.5";
  };
  deps.failure."0.1.5" = {
    backtrace = "0.3.34";
    failure_derive = "0.1.5";
  };
  deps.failure_derive."0.1.5" = {
    proc_macro2 = "0.4.30";
    quote = "0.6.13";
    syn = "0.15.42";
    synstructure = "0.10.2";
  };
  deps.finalfusion."0.8.1" = {
    byteorder = "1.3.2";
    fnv = "1.0.6";
    itertools = "0.8.0";
    memmap = "0.7.0";
    ndarray = "0.12.1";
    ordered_float = "1.0.2";
    rand = "0.6.5";
    rand_xorshift = "0.1.1";
    reductive = "0.2.0";
    serde = "1.0.98";
    toml = "0.5.1";
  };
  deps.finalfusion_utils."0.8.1" = {
    clap = "2.33.0";
    env_logger = "0.6.2";
    failure = "0.1.5";
    finalfusion = "0.8.1";
    getopts = "0.2.19";
    ndarray = "0.12.1";
    num_cpus = "1.10.1";
    rayon = "1.1.0";
    reductive = "0.2.0";
    stdinout = "0.4.0";
    toml = "0.5.1";
  };
  deps.fnv."1.0.6" = {};
  deps.fuchsia_cprng."0.1.1" = {};
  deps.getopts."0.2.19" = {
    unicode_width = "0.1.5";
  };
  deps.humantime."1.2.0" = {
    quick_error = "1.2.2";
  };
  deps.itertools."0.7.11" = {
    either = "1.5.2";
  };
  deps.itertools."0.8.0" = {
    either = "1.5.2";
  };
  deps.lapacke."0.2.0" = {
    lapacke_sys = "0.1.4";
    libc = "0.2.60";
    num_complex = "0.2.3";
  };
  deps.lapacke_sys."0.1.4" = {
    libc = "0.2.60";
  };
  deps.lazy_static."1.3.0" = {};
  deps.libc."0.2.60" = {};
  deps.log."0.4.8" = {
    cfg_if = "0.1.9";
  };
  deps.matrixmultiply."0.1.15" = {
    rawpointer = "0.1.0";
  };
  deps.memchr."2.2.1" = {};
  deps.memmap."0.7.0" = {
    libc = "0.2.60";
    winapi = "0.3.7";
  };
  deps.memoffset."0.5.1" = {
    rustc_version = "0.2.3";
  };
  deps.ndarray."0.12.1" = {
    blas_src = "0.2.1";
    cblas_sys = "0.1.4";
    itertools = "0.7.11";
    matrixmultiply = "0.1.15";
    num_complex = "0.2.3";
    num_traits = "0.2.8";
  };
  deps.ndarray_linalg."0.10.0" = {
    derive_new = "0.5.7";
    lapacke = "0.2.0";
    ndarray = "0.12.1";
    num_complex = "0.2.3";
    num_traits = "0.2.8";
    procedurals = "0.3.1";
    rand = "0.5.6";
  };
  deps.ndarray_parallel."0.9.0" = {
    ndarray = "0.12.1";
    rayon = "1.1.0";
  };
  deps.nodrop."0.1.13" = {};
  deps.num_complex."0.2.3" = {
    num_traits = "0.2.8";
    autocfg = "0.1.5";
  };
  deps.num_traits."0.2.8" = {
    autocfg = "0.1.5";
  };
  deps.num_cpus."1.10.1" = {
    libc = "0.2.60";
  };
  deps.ordered_float."1.0.2" = {
    num_traits = "0.2.8";
  };
  deps.proc_macro2."0.4.30" = {
    unicode_xid = "0.1.0";
  };
  deps.procedurals."0.3.1" = {
    quote = "0.6.13";
    syn = "0.14.9";
  };
  deps.quick_error."1.2.2" = {};
  deps.quote."0.6.13" = {
    proc_macro2 = "0.4.30";
  };
  deps.rand."0.5.6" = {
    rand_core = "0.3.1";
    cloudabi = "0.0.3";
    fuchsia_cprng = "0.1.1";
    libc = "0.2.60";
    winapi = "0.3.7";
  };
  deps.rand."0.6.5" = {
    rand_chacha = "0.1.1";
    rand_core = "0.4.0";
    rand_hc = "0.1.0";
    rand_isaac = "0.1.1";
    rand_jitter = "0.1.4";
    rand_os = "0.1.3";
    rand_pcg = "0.1.2";
    rand_xorshift = "0.1.1";
    autocfg = "0.1.5";
    libc = "0.2.60";
    winapi = "0.3.7";
  };
  deps.rand_chacha."0.1.1" = {
    rand_core = "0.3.1";
    autocfg = "0.1.5";
  };
  deps.rand_core."0.3.1" = {
    rand_core = "0.4.0";
  };
  deps.rand_core."0.4.0" = {};
  deps.rand_hc."0.1.0" = {
    rand_core = "0.3.1";
  };
  deps.rand_isaac."0.1.1" = {
    rand_core = "0.3.1";
  };
  deps.rand_jitter."0.1.4" = {
    rand_core = "0.4.0";
    libc = "0.2.60";
    winapi = "0.3.7";
  };
  deps.rand_os."0.1.3" = {
    rand_core = "0.4.0";
    rdrand = "0.4.0";
    cloudabi = "0.0.3";
    fuchsia_cprng = "0.1.1";
    libc = "0.2.60";
    winapi = "0.3.7";
  };
  deps.rand_pcg."0.1.2" = {
    rand_core = "0.4.0";
    autocfg = "0.1.5";
  };
  deps.rand_xorshift."0.1.1" = {
    rand_core = "0.3.1";
  };
  deps.rawpointer."0.1.0" = {};
  deps.rayon."1.1.0" = {
    crossbeam_deque = "0.6.3";
    either = "1.5.2";
    rayon_core = "1.5.0";
  };
  deps.rayon_core."1.5.0" = {
    crossbeam_deque = "0.6.3";
    crossbeam_queue = "0.1.2";
    crossbeam_utils = "0.6.6";
    lazy_static = "1.3.0";
    num_cpus = "1.10.1";
  };
  deps.rdrand."0.4.0" = {
    rand_core = "0.3.1";
  };
  deps.reductive."0.2.0" = {
    log = "0.4.8";
    ndarray = "0.12.1";
    ndarray_linalg = "0.10.0";
    ndarray_parallel = "0.9.0";
    num_traits = "0.2.8";
    ordered_float = "1.0.2";
    rand = "0.6.5";
    rand_xorshift = "0.1.1";
    rayon = "1.1.0";
  };
  deps.regex."1.2.1" = {
    aho_corasick = "0.7.6";
    memchr = "2.2.1";
    regex_syntax = "0.6.11";
    thread_local = "0.3.6";
  };
  deps.regex_syntax."0.6.11" = {};
  deps.rustc_demangle."0.1.15" = {};
  deps.rustc_version."0.2.3" = {
    semver = "0.9.0";
  };
  deps.scopeguard."1.0.0" = {};
  deps.semver."0.9.0" = {
    semver_parser = "0.7.0";
  };
  deps.semver_parser."0.7.0" = {};
  deps.serde."1.0.98" = {
    serde_derive = "1.0.98";
  };
  deps.serde_derive."1.0.98" = {
    proc_macro2 = "0.4.30";
    quote = "0.6.13";
    syn = "0.15.42";
  };
  deps.stdinout."0.4.0" = {};
  deps.strsim."0.8.0" = {};
  deps.syn."0.14.9" = {
    proc_macro2 = "0.4.30";
    quote = "0.6.13";
    unicode_xid = "0.1.0";
  };
  deps.syn."0.15.42" = {
    proc_macro2 = "0.4.30";
    quote = "0.6.13";
    unicode_xid = "0.1.0";
  };
  deps.synstructure."0.10.2" = {
    proc_macro2 = "0.4.30";
    quote = "0.6.13";
    syn = "0.15.42";
    unicode_xid = "0.1.0";
  };
  deps.termcolor."1.0.5" = {
    wincolor = "1.0.1";
  };
  deps.textwrap."0.11.0" = {
    unicode_width = "0.1.5";
  };
  deps.thread_local."0.3.6" = {
    lazy_static = "1.3.0";
  };
  deps.toml."0.5.1" = {
    serde = "1.0.98";
  };
  deps.unicode_width."0.1.5" = {};
  deps.unicode_xid."0.1.0" = {};
  deps.vec_map."0.8.1" = {};
  deps.winapi."0.3.7" = {
    winapi_i686_pc_windows_gnu = "0.4.0";
    winapi_x86_64_pc_windows_gnu = "0.4.0";
  };
  deps.winapi_i686_pc_windows_gnu."0.4.0" = {};
  deps.winapi_util."0.1.2" = {
    winapi = "0.3.7";
  };
  deps.winapi_x86_64_pc_windows_gnu."0.4.0" = {};
  deps.wincolor."1.0.1" = {
    winapi = "0.3.7";
    winapi_util = "0.1.2";
  };
}
