name: "Test"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        channel:
          - "https://nixos.org/channels/nixos-19.09"
          - "https://nixos.org/channels/nixos-unstable"
          - "https://nixos.org/channels/nixpkgs-unstable"
    steps:
    - uses: actions/checkout@v1
    - uses: cachix/install-nix-action@v6
    - run: nix-channel --add ${{ matrix.channel }} nixpkgs
    - run: nix-channel --update
    - run: cat /etc/nix/nix.conf
    - uses: cachix/cachix-action@releases/v3
      with:
        name: danieldk
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
        file: ci.nix
        attributes: buildOutputs